src:
  bot:
    token: !env "TELEGRAM_TOKEN:"
  main_flow:
    mini_app_url: !env "MINI_APP_URL:http://localhost:8080"
    channel_url: !env "CHANNEL_URL:https://t.me/telegram"
    support_username: !env "SUPPORT_USERNAME:telegram"
  admin_flow:
    admin_ids: !env "ADMIN_IDS:"
    products_path: !env "PRODUCTS_PATH:assets/products.xlsx"
  routes:
    products_path: !env "PRODUCTS_PATH:assets/products.xlsx"
rewire:
  log:
    sinks:
      - level: !env LOG_LEVEL:INFO
rewire_fastapi:
  server: "uvicorn"
  app:
    title: "Fyvessa Telegram Store"
    version: "1.0.0"
  uvicorn:
    port: 8080
    host: "0.0.0.0"
  patch:
    swagger_hierarchical_tags: true
    tag_prefixes: true
  middleware:
    cors:
      allow_origins: [ "*" ]
      allow_methods: [ "*" ]
      allow_headers: [ "*" ]
rewire_sqlmodel:
  url: !pyexec return getenv("DATABASE_URL").replace("sqlite://", "sqlite+aiosqlite://").replace("postgresql://", "postgresql+asyncpg://")
  expire_on_commit: false
  alembic:
    generate: true
    schema_migrations: true
    env:
      render_as_batch: true