import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.schema import Column, ForeignKeyConstraint, Index, MetaData, PrimaryKeyConstraint, Table
from sqlalchemy.sql.sqltypes import BigInteger, Boolean, Date, DateTime, Integer, Numeric, Text
from sqlmodel.sql.sqltypes import AutoString

revision = 'CoinAdminActivation'
down_revision = 'InviteeReward'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column(
            'referral_activation_reward_awarded_at',
            sa.DateTime(),
            nullable=True,
        ))
        batch_op.add_column(sa.Column(
            'referral_activation_reward_amount',
            sa.Numeric(scale=2),
            nullable=False,
            server_default=sa.text('0'),
        ))

    with op.batch_alter_table('cointransaction') as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_cointransaction_admin_id'),
            ['admin_id'],
            unique=False,
        )


def downgrade() -> None:
    with op.batch_alter_table('cointransaction') as batch_op:
        batch_op.drop_index(batch_op.f('ix_cointransaction_admin_id'))
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('referral_activation_reward_amount')
        batch_op.drop_column('referral_activation_reward_awarded_at')


_Meta = MetaData()
schema = {
    'appsetting': Table(
        'appsetting',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'key',
            AutoString(),
            nullable=False,
        ),
        Column(
            'value',
            AutoString(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_appsetting_key',
            'key',
            unique=False,
        ),
        Index(
            'uq_appsetting_key',
            'key',
            unique=True,
        ),
    ),
    'banner': Table(
        'banner',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'title',
            AutoString(),
            nullable=False,
        ),
        Column(
            'image_url',
            AutoString(),
            nullable=False,
        ),
        Column(
            'target_url',
            AutoString(),
            nullable=False,
        ),
        Column(
            'position',
            Integer(),
            nullable=False,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_banner_is_active',
            'is_active',
            unique=False,
        ),
        Index(
            'ix_banner_position',
            'position',
            unique=False,
        ),
    ),
    'category': Table(
        'category',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_category_is_active',
            'is_active',
            unique=False,
        ),
        Index(
            'ix_category_name',
            'name',
            unique=False,
        ),
    ),
    'promocode': Table(
        'promocode',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'code',
            AutoString(),
            nullable=False,
        ),
        Column(
            'partner_name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'user_discount_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'partner_reward_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        Column(
            'is_deleted',
            Boolean(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_promocode_code',
            'code',
            unique=False,
        ),
        Index(
            'ix_promocode_is_active',
            'is_active',
            unique=False,
        ),
        Index(
            'ix_promocode_is_deleted',
            'is_deleted',
            unique=False,
        ),
    ),
    'socialchannel': Table(
        'socialchannel',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'platform',
            AutoString(),
            nullable=False,
        ),
        Column(
            'account_name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'url',
            AutoString(),
            nullable=False,
        ),
        Column(
            'coin_reward',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'invitee_coin_reward',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'telegram_chat_id',
            AutoString(),
            nullable=True,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_socialchannel_platform',
            'platform',
            unique=False,
        ),
        Index(
            'ix_socialchannel_is_active',
            'is_active',
            unique=False,
        ),
    ),
    'user': Table(
        'user',
        _Meta,
        Column(
            'id',
            BigInteger(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'username',
            AutoString(),
            nullable=True,
        ),
        Column(
            'first_name',
            AutoString(),
            nullable=True,
        ),
        Column(
            'last_name',
            AutoString(),
            nullable=True,
        ),
        Column(
            'birth_date',
            Date(),
            nullable=True,
        ),
        Column(
            'phone_number',
            AutoString(),
            nullable=True,
        ),
        Column(
            'referrer_id',
            BigInteger(),
            nullable=True,
        ),
        Column(
            'referral_discount_awarded_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'referral_activation_reward_awarded_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'referral_activation_reward_amount',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'coin_balance',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'personal_discount_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['referrer_id'],
            [
                'user.id',
            ],
            name='fk_user_referrer_id_user',
        ),
        Index(
            'ix_user_referrer_id',
            'referrer_id',
            unique=False,
        ),
    ),
    'partnerpayout': Table(
        'partnerpayout',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'generated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'period_started_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'period_ended_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'promo_code_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'partner_name_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'promo_code_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'reward_percent_snapshot',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'orders_count',
            Integer(),
            nullable=False,
        ),
        Column(
            'orders_total',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'payout_amount',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'paid_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'paid_by_admin_id',
            BigInteger(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['promo_code_id'],
            [
                'promocode.id',
            ],
            name='fk_partnerpayout_promo_code_id_promocode',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_partnerpayout_paid_at',
            'paid_at',
            unique=False,
        ),
        Index(
            'ix_partnerpayout_period_ended_at',
            'period_ended_at',
            unique=False,
        ),
        Index(
            'uq_partnerpayout_promo_period',
            'promo_code_id',
            'period_ended_at',
            unique=True,
        ),
        Index(
            'ix_partnerpayout_promo_code_id',
            'promo_code_id',
            unique=False,
        ),
        Index(
            'ix_partnerpayout_generated_at',
            'generated_at',
            unique=False,
        ),
        Index(
            'ix_partnerpayout_status',
            'status',
            unique=False,
        ),
    ),
    'product': Table(
        'product',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'sku',
            AutoString(),
            nullable=False,
        ),
        Column(
            'category_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'description',
            Text(),
            nullable=False,
        ),
        Column(
            'characteristics',
            Text(),
            nullable=False,
        ),
        Column(
            'retail_price',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'wholesale_price',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'discount_price',
            Numeric(scale=2),
            nullable=True,
        ),
        Column(
            'image_url',
            AutoString(),
            nullable=True,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        Column(
            'is_popular',
            Boolean(),
            nullable=False,
        ),
        Column(
            'is_new',
            Boolean(),
            nullable=False,
        ),
        Column(
            'owner',
            AutoString(),
            nullable=False,
        ),
        Column(
            'owner_share_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'views_count',
            Integer(),
            nullable=False,
        ),
        Column(
            'cart_additions_count',
            Integer(),
            nullable=False,
        ),
        Column(
            'purchases_count',
            Integer(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['category_id'],
            [
                'category.id',
            ],
            name='fk_product_category_id_category',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_product_name',
            'name',
            unique=False,
        ),
        Index(
            'ix_product_is_active',
            'is_active',
            unique=False,
        ),
        Index(
            'ix_product_category_id',
            'category_id',
            unique=False,
        ),
        Index(
            'ix_product_sku',
            'sku',
            unique=False,
        ),
        Index(
            'ix_product_is_popular',
            'is_popular',
            unique=False,
        ),
        Index(
            'ix_product_is_new',
            'is_new',
            unique=False,
        ),
    ),
    'referralreward': Table(
        'referralreward',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'invited_user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'referrer_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'social_channel_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'reward_amount',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'invitee_reward_amount',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'verified_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'reviewed_by_admin_id',
            BigInteger(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['invited_user_id'],
            [
                'user.id',
            ],
            name='fk_referralreward_invited_user_id_user',
        ),
        ForeignKeyConstraint(
            ['referrer_id'],
            [
                'user.id',
            ],
            name='fk_referralreward_referrer_id_user',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['social_channel_id'],
            [
                'socialchannel.id',
            ],
            name='fk_referralreward_social_channel_id_socialchannel',
        ),
        Index(
            'ix_referralreward_referrer_id',
            'referrer_id',
            unique=False,
        ),
        Index(
            'ix_referralreward_status',
            'status',
            unique=False,
        ),
        Index(
            'ix_referralreward_social_channel_id',
            'social_channel_id',
            unique=False,
        ),
        Index(
            'uq_referralreward_invited_channel',
            'invited_user_id',
            'social_channel_id',
            unique=True,
        ),
        Index(
            'ix_referralreward_created_at',
            'created_at',
            unique=False,
        ),
        Index(
            'ix_referralreward_invited_user_id',
            'invited_user_id',
            unique=False,
        ),
    ),
    'availabilityrequest': Table(
        'availabilityrequest',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'requested_quantity',
            Integer(),
            nullable=True,
        ),
        Column(
            'available_quantity',
            Integer(),
            nullable=True,
        ),
        Column(
            'admin_id',
            BigInteger(),
            nullable=True,
        ),
        Column(
            'admin_comment',
            AutoString(),
            nullable=True,
        ),
        Column(
            'resolved_at',
            DateTime(),
            nullable=True,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_availabilityrequest_product_id_product',
        ),
        ForeignKeyConstraint(
            ['user_id'],
            [
                'user.id',
            ],
            name='fk_availabilityrequest_user_id_user',
        ),
        Index(
            'ix_availabilityrequest_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_availabilityrequest_user_id',
            'user_id',
            unique=False,
        ),
        Index(
            'ix_availabilityrequest_status',
            'status',
            unique=False,
        ),
    ),
    'cartitem': Table(
        'cartitem',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'quantity',
            Integer(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_cartitem_product_id_product',
        ),
        ForeignKeyConstraint(
            ['user_id'],
            [
                'user.id',
            ],
            name='fk_cartitem_user_id_user',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_cartitem_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_cartitem_user_id',
            'user_id',
            unique=False,
        ),
    ),
    'favorite': Table(
        'favorite',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_favorite_product_id_product',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['user_id'],
            [
                'user.id',
            ],
            name='fk_favorite_user_id_user',
        ),
        Index(
            'ix_favorite_user_id',
            'user_id',
            unique=False,
        ),
        Index(
            'ix_favorite_product_id',
            'product_id',
            unique=False,
        ),
    ),
    'order': Table(
        'order',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'number',
            AutoString(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'payment_status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'shipping_status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'recipient_first_name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'recipient_last_name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'recipient_phone_number',
            AutoString(),
            nullable=False,
        ),
        Column(
            'delivery_method',
            AutoString(),
            nullable=False,
        ),
        Column(
            'pickup_point_address',
            Text(),
            nullable=False,
        ),
        Column(
            'promo_code_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'partner_payout_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'discount_mode',
            AutoString(),
            nullable=False,
        ),
        Column(
            'product_discount_total',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'personal_discount_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'promo_discount_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'coins_used',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'subtotal',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'paid_total',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'wholesale_total',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'net_profit',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'diana_share',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'bulat_share',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'partner_reward',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'purchase_coin_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'purchase_coins_awarded',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'payment_reported_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'paid_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'paid_by_admin_id',
            BigInteger(),
            nullable=True,
        ),
        Column(
            'shipped_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'delivered_at',
            DateTime(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['partner_payout_id'],
            [
                'partnerpayout.id',
            ],
            name='fk_order_partner_payout_id_partnerpayout',
        ),
        ForeignKeyConstraint(
            ['promo_code_id'],
            [
                'promocode.id',
            ],
            name='fk_order_promo_code_id_promocode',
        ),
        ForeignKeyConstraint(
            ['user_id'],
            [
                'user.id',
            ],
            name='fk_order_user_id_user',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_order_shipping_status',
            'shipping_status',
            unique=False,
        ),
        Index(
            'ix_order_status',
            'status',
            unique=False,
        ),
        Index(
            'ix_order_number',
            'number',
            unique=False,
        ),
        Index(
            'ix_order_created_at',
            'created_at',
            unique=False,
        ),
        Index(
            'ix_order_paid_at',
            'paid_at',
            unique=False,
        ),
        Index(
            'ix_order_partner_payout_id',
            'partner_payout_id',
            unique=False,
        ),
        Index(
            'ix_order_shipped_at',
            'shipped_at',
            unique=False,
        ),
        Index(
            'ix_order_user_id',
            'user_id',
            unique=False,
        ),
        Index(
            'ix_order_payment_status',
            'payment_status',
            unique=False,
        ),
        Index(
            'ix_order_delivered_at',
            'delivered_at',
            unique=False,
        ),
    ),
    'productview': Table(
        'productview',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'viewed_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['user_id'],
            [
                'user.id',
            ],
            name='fk_productview_user_id_user',
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_productview_product_id_product',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_productview_user_id',
            'user_id',
            unique=False,
        ),
        Index(
            'ix_productview_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_productview_viewed_at',
            'viewed_at',
            unique=False,
        ),
    ),
    'cointransaction': Table(
        'cointransaction',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'order_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'social_channel_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'referral_reward_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'admin_id',
            BigInteger(),
            nullable=True,
        ),
        Column(
            'amount',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'balance_after',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'reason',
            AutoString(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['user_id'],
            [
                'user.id',
            ],
            name='fk_cointransaction_user_id_user',
        ),
        ForeignKeyConstraint(
            ['order_id'],
            [
                'order.id',
            ],
            name='fk_cointransaction_order_id_order',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['social_channel_id'],
            [
                'socialchannel.id',
            ],
            name='fk_cointransaction_social_channel_id_socialchannel',
        ),
        ForeignKeyConstraint(
            ['referral_reward_id'],
            [
                'referralreward.id',
            ],
            name='fk_cointransaction_referral_reward_id_referralreward',
        ),
        Index(
            'ix_cointransaction_social_channel_id',
            'social_channel_id',
            unique=False,
        ),
        Index(
            'ix_cointransaction_referral_reward_id',
            'referral_reward_id',
            unique=False,
        ),
        Index(
            'ix_cointransaction_created_at',
            'created_at',
            unique=False,
        ),
        Index(
            'ix_cointransaction_user_id',
            'user_id',
            unique=False,
        ),
        Index(
            'ix_cointransaction_order_id',
            'order_id',
            unique=False,
        ),
        Index(
            'ix_cointransaction_admin_id',
            'admin_id',
            unique=False,
        ),
    ),
    'orderitem': Table(
        'orderitem',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'order_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'quantity',
            Integer(),
            nullable=False,
        ),
        Column(
            'sku_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'product_name_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'category_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'retail_price_snapshot',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'sale_price_snapshot',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'wholesale_price_snapshot',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'owner_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'owner_share_percent_snapshot',
            Numeric(scale=2),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_orderitem_product_id_product',
        ),
        ForeignKeyConstraint(
            ['order_id'],
            [
                'order.id',
            ],
            name='fk_orderitem_order_id_order',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_orderitem_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_orderitem_order_id',
            'order_id',
            unique=False,
        ),
    ),
}
