# type: ignore
"""Dev

Revision ID: KGKmiwvPOQKu155RNw8bGJg
Revises: root_initial
Create Date: 2026-08-09 15:32:48.411604
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'KGKmiwvPOQKu155RNw8bGJg'
down_revision: Union[str, None] = 'root_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    op.create_table(
        'customer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('coin_balance', sa.Numeric(scale=2), nullable=False),
        sa.Column('personal_discount_percent', sa.Numeric(scale=2), nullable=False),
        sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_referral_code'), ['referral_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_user_id'), ['user_id'], unique=False)

    op.create_table(
        'payout',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paid_at', sa.DateTime(), nullable=False),
        sa.Column('recipient_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('recorded_by_admin_id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_recipient_name'), ['recipient_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_recipient_type'), ['recipient_type'], unique=False)

    op.create_table(
        'promocode',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('partner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('customer_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('partner_reward_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('promocode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocode_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocode_is_active'), ['is_active'], unique=False)

    op.create_table(
        'order',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('promo_code_id', sa.Integer(), nullable=True),
        sa.Column('discount_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('product_discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('personal_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('promo_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('coins_used', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('paid_total', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('wholesale_total', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('diana_share', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('bulat_share', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('partner_reward', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('payment_reported_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.Column('paid_by_admin_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['promo_code_id'], ['promocode.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)

    op.create_table(
        'product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('characteristics', sa.Text(), nullable=False),
        sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('discount_price', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_popular', sa.Boolean(), nullable=False),
        sa.Column('is_recommended', sa.Boolean(), nullable=False),
        sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_share_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('views_count', sa.Integer(), nullable=False),
        sa.Column('cart_additions_count', sa.Integer(), nullable=False),
        sa.Column('purchases_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_popular'), ['is_popular'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_recommended'), ['is_recommended'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)

    op.create_table(
        'referral',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('inviter_id', sa.Integer(), nullable=False),
        sa.Column('invitee_id', sa.Integer(), nullable=False),
        sa.Column('subscription_confirmed', sa.Boolean(), nullable=False),
        sa.Column('reward_granted', sa.Boolean(), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invitee_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['inviter_id'], ['customer.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_invitee_id'), ['invitee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_inviter_id'), ['inviter_id'], unique=False)

    op.create_table(
        'supportrequest',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('closed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('supportrequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supportrequest_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supportrequest_status'), ['status'], unique=False)

    op.create_table(
        'availabilityrequest',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('requested_quantity', sa.Integer(), nullable=True),
        sa.Column('available_quantity', sa.Integer(), nullable=True),
        sa.Column('admin_id', sa.BigInteger(), nullable=True),
        sa.Column('admin_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('availabilityrequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availabilityrequest_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availabilityrequest_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availabilityrequest_status'), ['status'], unique=False)

    op.create_table(
        'cartitem',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cartitem_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cartitem_product_id'), ['product_id'], unique=False)

    op.create_table(
        'cointransaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('cointransaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cointransaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cointransaction_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cointransaction_order_id'), ['order_id'], unique=False)

    op.create_table(
        'favorite',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_product_id'), ['product_id'], unique=False)

    op.create_table(
        'orderitem',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('sku_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('product_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('retail_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('sale_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('wholesale_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('owner_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_share_percent_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orderitem_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orderitem_product_id'), ['product_id'], unique=False)

    op.create_table(
        'productview',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('viewed_at', sa.DateTime(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('productview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productview_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productview_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productview_viewed_at'), ['viewed_at'], unique=False)

    op.create_table(
        'review',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_product_id'))
        batch_op.drop_index(batch_op.f('ix_review_order_id'))
        batch_op.drop_index(batch_op.f('ix_review_is_published'))
        batch_op.drop_index(batch_op.f('ix_review_customer_id'))

    op.drop_table('review')
    with op.batch_alter_table('productview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productview_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_productview_product_id'))
        batch_op.drop_index(batch_op.f('ix_productview_customer_id'))

    op.drop_table('productview')
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orderitem_product_id'))
        batch_op.drop_index(batch_op.f('ix_orderitem_order_id'))

    op.drop_table('orderitem')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_product_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_customer_id'))

    op.drop_table('favorite')
    with op.batch_alter_table('cointransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cointransaction_order_id'))
        batch_op.drop_index(batch_op.f('ix_cointransaction_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cointransaction_created_at'))

    op.drop_table('cointransaction')
    with op.batch_alter_table('cartitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cartitem_product_id'))
        batch_op.drop_index(batch_op.f('ix_cartitem_customer_id'))

    op.drop_table('cartitem')
    with op.batch_alter_table('availabilityrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availabilityrequest_status'))
        batch_op.drop_index(batch_op.f('ix_availabilityrequest_product_id'))
        batch_op.drop_index(batch_op.f('ix_availabilityrequest_customer_id'))

    op.drop_table('availabilityrequest')
    with op.batch_alter_table('supportrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supportrequest_status'))
        batch_op.drop_index(batch_op.f('ix_supportrequest_customer_id'))

    op.drop_table('supportrequest')
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_referral_invitee_id'))

    op.drop_table('referral')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_is_recommended'))
        batch_op.drop_index(batch_op.f('ix_product_is_popular'))
        batch_op.drop_index(batch_op.f('ix_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))

    op.drop_table('product')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_payment_status'))
        batch_op.drop_index(batch_op.f('ix_order_paid_at'))
        batch_op.drop_index(batch_op.f('ix_order_number'))
        batch_op.drop_index(batch_op.f('ix_order_customer_id'))
        batch_op.drop_index(batch_op.f('ix_order_created_at'))

    op.drop_table('order')
    with op.batch_alter_table('promocode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocode_is_active'))
        batch_op.drop_index(batch_op.f('ix_promocode_code'))

    op.drop_table('promocode')
    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_recipient_type'))
        batch_op.drop_index(batch_op.f('ix_payout_recipient_name'))
        batch_op.drop_index(batch_op.f('ix_payout_paid_at'))

    op.drop_table('payout')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_referral_code'))

    op.drop_table('customer')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index(batch_op.f('ix_category_is_active'))

    op.drop_table('category')
    # ### end Alembic commands ###


from sqlalchemy.sql.elements import quoted_name
from sqlalchemy.sql.schema import Table
from sqlalchemy.sql.schema import MetaData
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.sqltypes import Integer
from sqlmodel.sql.sqltypes import AutoString
from sqlalchemy.sql.sqltypes import Boolean
from sqlalchemy.sql.sqltypes import DateTime
from sqlalchemy.sql.schema import PrimaryKeyConstraint
from sqlalchemy.sql.schema import Index
from sqlalchemy.sql.sqltypes import BigInteger
from sqlalchemy.sql.sqltypes import Date
from sqlalchemy.sql.sqltypes import Numeric
from sqlalchemy.sql.schema import ForeignKeyConstraint
from sqlalchemy.sql.sqltypes import Text

_Meta = MetaData()
schema = {
    'category': Table(
        'category',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'image_url',
            AutoString(),
            nullable=True,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_category_is_active',
            'is_active',
            unique=False,
        ),
        Index(
            'ix_category_name',
            'name',
            unique=False,
        ),
    ),
    'customer': Table(
        'customer',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'user_id',
            BigInteger(),
            nullable=False,
        ),
        Column(
            'username',
            AutoString(),
            nullable=True,
        ),
        Column(
            'first_name',
            AutoString(),
            nullable=True,
        ),
        Column(
            'last_name',
            AutoString(),
            nullable=True,
        ),
        Column(
            'birth_date',
            Date(),
            nullable=True,
        ),
        Column(
            'phone_number',
            AutoString(),
            nullable=True,
        ),
        Column(
            'coin_balance',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'personal_discount_percent',
            Numeric(scale=2),
            nullable=False,
        ),
        Column(
            'referral_code',
            AutoString(),
            nullable=True,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_customer_referral_code',
            'referral_code',
            unique=False,
        ),
        Index(
            'ix_customer_user_id',
            'user_id',
            unique=False,
        ),
    ),
    'payout': Table(
        'payout',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'paid_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'recipient_type',
            AutoString(),
            nullable=False,
        ),
        Column(
            'recipient_name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'amount',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'note',
            AutoString(),
            nullable=True,
        ),
        Column(
            'recorded_by_admin_id',
            BigInteger(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_payout_paid_at',
            'paid_at',
            unique=False,
        ),
        Index(
            'ix_payout_recipient_name',
            'recipient_name',
            unique=False,
        ),
        Index(
            'ix_payout_recipient_type',
            'recipient_type',
            unique=False,
        ),
    ),
    'promocode': Table(
        'promocode',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'code',
            AutoString(),
            nullable=False,
        ),
        Column(
            'partner_name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'customer_discount_percent',
            Numeric(precision=5, scale=2),
            nullable=False,
        ),
        Column(
            'partner_reward_percent',
            Numeric(precision=5, scale=2),
            nullable=False,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_promocode_code',
            'code',
            unique=False,
        ),
        Index(
            'ix_promocode_is_active',
            'is_active',
            unique=False,
        ),
    ),
    'order': Table(
        'order',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'number',
            AutoString(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'payment_status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'promo_code_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'discount_mode',
            AutoString(),
            nullable=False,
        ),
        Column(
            'product_discount_total',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'personal_discount_percent',
            Numeric(precision=5, scale=2),
            nullable=False,
        ),
        Column(
            'promo_discount_percent',
            Numeric(precision=5, scale=2),
            nullable=False,
        ),
        Column(
            'coins_used',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'subtotal',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'paid_total',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'wholesale_total',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'net_profit',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'diana_share',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'bulat_share',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'partner_reward',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'payment_reported_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'paid_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'paid_by_admin_id',
            BigInteger(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_order_customer_id_customer',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['promo_code_id'],
            [
                'promocode.id',
            ],
            name='fk_order_promo_code_id_promocode',
        ),
        Index(
            'ix_order_created_at',
            'created_at',
            unique=False,
        ),
        Index(
            'ix_order_paid_at',
            'paid_at',
            unique=False,
        ),
        Index(
            'ix_order_status',
            'status',
            unique=False,
        ),
        Index(
            'ix_order_payment_status',
            'payment_status',
            unique=False,
        ),
        Index(
            'ix_order_customer_id',
            'customer_id',
            unique=False,
        ),
        Index(
            'ix_order_number',
            'number',
            unique=False,
        ),
    ),
    'product': Table(
        'product',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'sku',
            AutoString(),
            nullable=False,
        ),
        Column(
            'category_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'description',
            Text(),
            nullable=False,
        ),
        Column(
            'characteristics',
            Text(),
            nullable=False,
        ),
        Column(
            'retail_price',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'wholesale_price',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'discount_price',
            Numeric(precision=12, scale=2),
            nullable=True,
        ),
        Column(
            'image_url',
            AutoString(),
            nullable=True,
        ),
        Column(
            'is_active',
            Boolean(),
            nullable=False,
        ),
        Column(
            'is_popular',
            Boolean(),
            nullable=False,
        ),
        Column(
            'is_recommended',
            Boolean(),
            nullable=False,
        ),
        Column(
            'owner',
            AutoString(),
            nullable=False,
        ),
        Column(
            'owner_share_percent',
            Numeric(precision=5, scale=2),
            nullable=False,
        ),
        Column(
            'views_count',
            Integer(),
            nullable=False,
        ),
        Column(
            'cart_additions_count',
            Integer(),
            nullable=False,
        ),
        Column(
            'purchases_count',
            Integer(),
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['category_id'],
            [
                'category.id',
            ],
            name='fk_product_category_id_category',
        ),
        Index(
            'ix_product_is_recommended',
            'is_recommended',
            unique=False,
        ),
        Index(
            'ix_product_is_popular',
            'is_popular',
            unique=False,
        ),
        Index(
            'ix_product_is_active',
            'is_active',
            unique=False,
        ),
        Index(
            'ix_product_sku',
            'sku',
            unique=False,
        ),
        Index(
            'ix_product_name',
            'name',
            unique=False,
        ),
        Index(
            'ix_product_category_id',
            'category_id',
            unique=False,
        ),
    ),
    'referral': Table(
        'referral',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'inviter_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'invitee_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'subscription_confirmed',
            Boolean(),
            nullable=False,
        ),
        Column(
            'reward_granted',
            Boolean(),
            nullable=False,
        ),
        Column(
            'confirmed_at',
            DateTime(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['invitee_id'],
            [
                'customer.id',
            ],
            name='fk_referral_invitee_id_customer',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['inviter_id'],
            [
                'customer.id',
            ],
            name='fk_referral_inviter_id_customer',
        ),
        Index(
            'ix_referral_inviter_id',
            'inviter_id',
            unique=False,
        ),
        Index(
            'ix_referral_invitee_id',
            'invitee_id',
            unique=False,
        ),
    ),
    'supportrequest': Table(
        'supportrequest',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'subject',
            AutoString(),
            nullable=False,
        ),
        Column(
            'message',
            Text(),
            nullable=False,
        ),
        Column(
            'closed_at',
            DateTime(),
            nullable=True,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_supportrequest_customer_id_customer',
        ),
        Index(
            'ix_supportrequest_status',
            'status',
            unique=False,
        ),
        Index(
            'ix_supportrequest_customer_id',
            'customer_id',
            unique=False,
        ),
    ),
    'availabilityrequest': Table(
        'availabilityrequest',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'status',
            AutoString(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'requested_quantity',
            Integer(),
            nullable=True,
        ),
        Column(
            'available_quantity',
            Integer(),
            nullable=True,
        ),
        Column(
            'admin_id',
            BigInteger(),
            nullable=True,
        ),
        Column(
            'admin_comment',
            AutoString(),
            nullable=True,
        ),
        Column(
            'resolved_at',
            DateTime(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_availabilityrequest_product_id_product',
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_availabilityrequest_customer_id_customer',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_availabilityrequest_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_availabilityrequest_customer_id',
            'customer_id',
            unique=False,
        ),
        Index(
            'ix_availabilityrequest_status',
            'status',
            unique=False,
        ),
    ),
    'cartitem': Table(
        'cartitem',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'updated_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'quantity',
            Integer(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_cartitem_product_id_product',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_cartitem_customer_id_customer',
        ),
        Index(
            'ix_cartitem_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_cartitem_customer_id',
            'customer_id',
            unique=False,
        ),
    ),
    'cointransaction': Table(
        'cointransaction',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'order_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'amount',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'balance_after',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'reason',
            AutoString(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_cointransaction_customer_id_customer',
        ),
        ForeignKeyConstraint(
            ['order_id'],
            [
                'order.id',
            ],
            name='fk_cointransaction_order_id_order',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_cointransaction_customer_id',
            'customer_id',
            unique=False,
        ),
        Index(
            'ix_cointransaction_order_id',
            'order_id',
            unique=False,
        ),
        Index(
            'ix_cointransaction_created_at',
            'created_at',
            unique=False,
        ),
    ),
    'favorite': Table(
        'favorite',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_favorite_customer_id_customer',
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_favorite_product_id_product',
        ),
        Index(
            'ix_favorite_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_favorite_customer_id',
            'customer_id',
            unique=False,
        ),
    ),
    'orderitem': Table(
        'orderitem',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'order_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'quantity',
            Integer(),
            nullable=False,
        ),
        Column(
            'sku_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'product_name_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'category_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'retail_price_snapshot',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'sale_price_snapshot',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'wholesale_price_snapshot',
            Numeric(precision=12, scale=2),
            nullable=False,
        ),
        Column(
            'owner_snapshot',
            AutoString(),
            nullable=False,
        ),
        Column(
            'owner_share_percent_snapshot',
            Numeric(precision=5, scale=2),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_orderitem_product_id_product',
        ),
        ForeignKeyConstraint(
            ['order_id'],
            [
                'order.id',
            ],
            name='fk_orderitem_order_id_order',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_orderitem_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_orderitem_order_id',
            'order_id',
            unique=False,
        ),
    ),
    'productview': Table(
        'productview',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'viewed_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_productview_customer_id_customer',
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_productview_product_id_product',
        ),
        Index(
            'ix_productview_product_id',
            'product_id',
            unique=False,
        ),
        Index(
            'ix_productview_customer_id',
            'customer_id',
            unique=False,
        ),
        Index(
            'ix_productview_viewed_at',
            'viewed_at',
            unique=False,
        ),
    ),
    'review': Table(
        'review',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'customer_id',
            Integer(),
            nullable=False,
        ),
        Column(
            'product_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'order_id',
            Integer(),
            nullable=True,
        ),
        Column(
            'rating',
            Integer(),
            nullable=False,
        ),
        Column(
            'text',
            Text(),
            nullable=False,
        ),
        Column(
            'is_published',
            Boolean(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['order_id'],
            [
                'order.id',
            ],
            name='fk_review_order_id_order',
        ),
        ForeignKeyConstraint(
            ['customer_id'],
            [
                'customer.id',
            ],
            name='fk_review_customer_id_customer',
        ),
        ForeignKeyConstraint(
            ['product_id'],
            [
                'product.id',
            ],
            name='fk_review_product_id_product',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
        Index(
            'ix_review_customer_id',
            'customer_id',
            unique=False,
        ),
        Index(
            'ix_review_is_published',
            'is_published',
            unique=False,
        ),
        Index(
            'ix_review_order_id',
            'order_id',
            unique=False,
        ),
        Index(
            'ix_review_product_id',
            'product_id',
            unique=False,
        ),
    ),
}
